ALTER TYPE "KnowledgeSourceType" ADD VALUE IF NOT EXISTS 'PDF';
ALTER TYPE "KnowledgeSourceType" ADD VALUE IF NOT EXISTS 'DOCX';
ALTER TYPE "KnowledgeSourceType" ADD VALUE IF NOT EXISTS 'PPTX';
ALTER TYPE "KnowledgeSourceType" ADD VALUE IF NOT EXISTS 'HTML';
